name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # TAHAP 1: PABRIK CLOUD (Build & Push)
  build-and-push:
    name: 🏗️ Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Source Code
        uses: actions/checkout@v4

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 📦 Build, Tag, and Push
        run: |
          # 1. Build image dari Dockerfile
          docker compose build
          
          # 2. Cetak stiker kedua pakai ID Unik GitHub (Arsip History)
          docker tag akmalaufa/portfolio-akmal:latest akmalaufa/portfolio-akmal:${{ github.sha }}
          
          # 3. Kirim image :latest ke Docker Hub (Buat dipakai VPS)
          docker push akmalaufa/portfolio-akmal:latest
          
          # 4. Kirim image ID Unik ke Docker Hub (Buat disimpan di Gudang Arsip)
          docker push akmalaufa/portfolio-akmal:${{ github.sha }}

  # TAHAP 2: KURIR DEPLOYMENT (Masuk VPS)
  deploy:
    name: 🚀 Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: 🌐 Eksekusi Docker di VPS (Via SSH ProxyJump)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          # 1. Bikin folder SSH & masukin gembok rahasia
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # 2. Tiru persis konfigurasi dari laptop Axioo lu (Jalur Tikus)
          cat <<EOF > ~/.ssh/config
          Host hosted.tirtagt.com
            StrictHostKeyChecking no

          Host akmal.hosted.tirtagt.com
            HostName akmal.hosted.tirtagt.com
            ProxyJump ssh-relay@hosted.tirtagt.com
            User tct_client
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/id_ed25519
          EOF
          
          # 3. Kencengin permission config
          chmod 600 ~/.ssh/config

          # 4. Eksekusi Remote (Lompat dari GitHub -> Relay -> VPS)
          ssh tct_client@akmal.hosted.tirtagt.com "cd ~/project_portfolio && docker compose pull && docker compose up -d && docker image prune -af"
